DROP TABLE IF EXISTS acceleration;
DROP TABLE IF EXISTS stax;
DROP TABLE IF EXISTS counters;
DROP TABLE IF EXISTS board_wipes;
DROP TABLE IF EXISTS tutors;
DROP TABLE IF EXISTS card_advantage;
DROP TABLE IF EXISTS cards;
