DROP TABLE IF EXISTS acceleration;
DROP TABLE IF EXISTS stax;
DROP TABLE IF EXISTS counters;
DROP TABLE IF EXISTS board_wipes;
DROP TABLE IF EXISTS tutors;
DROP TABLE IF EXISTS card_advantage;
DROP TABLE foreign_data;
DROP TABLE set_translations;
DROP TABLE legalities;
DROP TABLE rulings;
DROP TABLE prices;
DROP TABLE tokens;
DROP TABLE cards;
DROP TABLE sets;
